## 1.1 arange
- array의 범위를 지정하여, 값의 List를 생성하는 명령어

In [1]:
import numpy as np

In [4]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 ~ 29까지 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
np.arange(0,5,0.5) # floating point도 표시가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
np.arange(30).reshape(5,6)

In [8]:
np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## 1.2 ones,zeros and empty

In [10]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((2,5)) # 2 by 5 - ones matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((5,5)) # 5 by 5 -empty matrix를 생성하는데 선언과 동시에 초기화를 시켜주지 않는다.

array([[9.12404688e-312, 7.41098469e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307],
       [1.15998412e-028, 2.44171989e+232, 8.00801729e+159,
        9.45007090e-076, 6.98345624e-077],
       [6.98345624e-077, 6.01391519e-154, 7.06673073e-096,
        7.06652016e-096, 7.18988929e+140],
       [6.01347002e-154, 6.98345625e-077, 6.98345624e-077,
        1.95360427e-109, 2.86752281e+161],
       [2.78225500e+296, 9.80058441e+252, 1.23971686e+224,
        1.82358708e-306, 3.20552953e-317]])

## 1.3 something_like
- 기존에 있던 Matrix와 같은 shape 크기 만큼 1,0 또는 empty array를 반환

In [16]:
test_matrix = np.arange(30).reshape(5,6)

In [17]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [19]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## 1.4 identity
- 단위 행렬(i 행렬)을 생성

In [21]:
np.identity(5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1.5 eye
- 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

In [22]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [25]:
np.eye(3,5,k=2) # k: start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(3) # = identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1.6 diag
- 대각 행렬을 추출

In [27]:
a = np.arange(25).reshape(5,5)

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
np.diag(a) # a 변수의 대각 원소들을 추출

array([ 0,  6, 12, 18, 24])

## 1.7 random sampling

In [30]:
# 0 ~ 1 사이의 균등분포 10개의 값들을 샘플링 
np.random.uniform(0,1,10).reshape(2,5)

array([[0.57294655, 0.54546018, 0.6757099 , 0.64283977, 0.154998  ],
       [0.67576694, 0.13701496, 0.2865191 , 0.3497238 , 0.16031237]])

In [31]:
# 0 ~ 1 사이의 정규분포 10개의 값들을 샘플링
# 평균이 0이고, 정규분포가 1인 10개의 값들을 샘플링
np.random.normal(0,1,10).reshape(2,5)

array([[-0.93039654,  0.13208771,  1.63427299,  0.28370039, -0.43000591],
       [ 0.00462309, -0.89075023,  0.23349788,  0.79753066,  0.85180171]])

# 2. operation functions
- 넘파이의 계산함수

## 2.1 sum

In [32]:
test_array = np.arange(1,11)

In [33]:
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
test_array.sum() # dtype 지정 

55

## 2.2 axis
- 모든 operation function을 실행할 때 기준이 되는 dimension 축
![test](./img/axis.png)


In [35]:
test_array = np.arange(1,13).reshape(3,4)

In [36]:
test_array.sum(axis=1) # 기존의 벡터 즉, 벡터를 기준으로

array([10, 26, 42])

In [37]:
test_array.sum(axis=0) # row 축을 기준으로 

array([15, 18, 21, 24])

In [38]:
test_array1 = np.array([1,2,3,4])

In [39]:
test_array1.shape

(4,)

In [42]:
test_array1.sum(axis=0)

10

In [43]:
test_array2 = np.arange(0,20).reshape(2,2,5)

In [44]:
test_array2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [45]:
test_array2.shape

(2, 2, 5)

In [46]:
test_array2.sum(axis=2) # 벡터의 형태를 기준

array([[10, 35],
       [60, 85]])

In [47]:
test_array2.sum(axis=1) # 열의 축을 기준으로

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33]])

In [48]:
test_array2.sum(axis=0) # matrix 형태로 변형

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

![test](./img/axis2.png)

In [49]:
test_array = np.arange(1,13).reshape(3,4)

## 2.3 mean & std

In [50]:
test_array.mean()

6.5

In [51]:
test_array.std()

3.452052529534663

## 2.4 Mathematical functions
![test](./img/연산자.png)

## 2.5 concatenate
- Numpy array를 합치는 함수
![test](./img/concat.png)

In [57]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b)) #넘파이 배열을 수직적으로 합친다

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b)) # 넘파이를 수평적으로 합친다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [61]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])